HOURS_PER_MONTH = 730
EBS_GP3_PER_GB_MONTH = 0.08
ELASTIC_IP_PER_HOUR = 0.005
ELASTIC_IP_MONTHLY = ELASTIC_IP_PER_HOUR * HOURS_PER_MONTH
STOPPED_INSTANCE_ESTIMATED_MONTHLY = 0.0

REQUIRED_TAGS = [
    "Project",
    "Environment",
    "Owner"
]
